### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by ArneKoeckeritz** [KeepSafe/ReLinker#21] opened 2016-06-21 08:02 UTC
Hi guys,

i want to report a problem that occures when my App (de.komoot.android) runs on a device with your keepsafe app.

Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/data/de.komoot.android/app_lib/librealm-jni.so" not found
       at java.lang.Runtime.load(Runtime.java:333)
       at java.lang.System.load(System.java:512)
       at com.getkeepsafe.relinker.SystemLibraryLoader.loadPath(SourceFile:29)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(SourceFile:200)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(SourceFile:140)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(SourceFile:70)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(SourceFile:51)
       at io.realm.internal.RealmCore.loadLibrary(SourceFile:89)
       at io.realm.RealmConfiguration$Builder.(SourceFile:352)
       at de.komoot.android.realm.KmtRealmHelper.getRealmConfiguration(SourceFile:135)
       at de.komoot.android.realm.KmtRealmMigration.initialMigrationCheck(SourceFile:71)
       at de.komoot.android.KomootApplication.onCreate(SourceFile:157)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4730)
       at android.app.ActivityThread.access$1600(ActivityThread.java:175)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5602)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)

More Infos on crashlytics:
http://crashes.to/s/d64ee5fe96f

My App is using realm which cant load his native library so file.
It would be cool if you together with the realm guys can solve this issue.

Best regards
Arne

**Comment by xiphirx** [comment] 2016-06-21 18:56
Hi!

Please make sure your APK is properly packaged and targets the correct architectures that you support. You can verify the APK is properly packaged by renaming your release APK to `something.zip` and unzipping the contents. Afterwards, please verify that the architectures you support are present in `libs/` and the libraries you need are in each of the architecture folders.

Also, are you able to reproduce this locally?

**Comment by ArneKoeckeritz** [comment] 2016-06-22 21:27
Its not a packaging problem. Every .so lib is packed into the apk. Realm works properly on all cpu architetures. Have a look at realm.io to get an introduction about what realm is and why this is very important and widly used library.

**Comment by xiphirx** [comment] 2016-06-22 21:33
Is the app distributed with ABI splits? or are all libraries for each architecture present in the APK?

**Comment by ArneKoeckeritz** [comment] 2016-07-05 07:18
No it isn't.
All so libs are present. This crashes does only happen on devices with the getkeepsafe software.

**Comment by NirpE** [comment] 2017-01-05 07:05
I have seen exact trace too with my customers.

**Comment by xiphirx** [comment] 2017-01-06 04:37
This issue is quite old at this point and I'm unsure what version the given stack trace is referring to so I'm going to close this issue. If you are using the latest version of the library and have more information to share please open a new issue.

**Closed by xiphirx** 2017-01-06 04:37 UTC

**Comment by NirpE** [comment] 2017-01-06 06:54
In my case this crash has been caused by a rooted device on customer using XposedBridge. So not sure if a hostile user, if so the crash is more than a welcome.

**Comment by xiphirx** [comment] 2017-01-06 07:27
I would ignore all rooted devices, especially those with Xposed. You dont have a deterministic system at that point.

**Comment by jangc** [comment] 2017-03-21 20:43
Hi, 

I have a similar problem.

"/data/data/com.funanduseful.earlybirdalarm/app_lib/librealm-jni.so.2.3.1" not found

Galaxy Grand-Max
Galaxy J5

Not rooted (from fabric)
No ABI splits

I found 5 so files("librealm-jni.so" in arm64-v8a, armeabi-v7a, mips, x86, x86_64) when unzip my apk.

**Comment by xiphirx** [comment] 2017-03-21 21:24
@jangc please create another issue with the full stack trace and other details

**Comment by jangc** [comment] 2017-03-21 21:28
@xiphirx Ok, but there are almost same stack track. 
I'll create another.

**Comment by jangc** [comment] 2017-03-21 22:05
@xiphirx Wow sorry. It's my mistake!
